version: '3.8'

services:
  api:
    container_name: handbook-api
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the name of your Dockerfile
    image: handbook-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt # Recommended for easier backup/inspection